/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './features/**/*.{js,jsx,ts,tsx}',
    './shared/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#f8f3f0',
        backgroundMuted: '#f3ece7',
        surface: '#fffdfa',
        surfaceMuted: '#f6eeea',
        surfaceAccent: '#f4e7dd',
        input: '#fffaf7',
        text: '#2f2622',
        textMuted: '#6d5c52',
        textSoft: '#9a887d',
        primary: '#b65a12',
        primaryStrong: '#9d4300',
        primarySoft: '#faede2',
        border: '#eaded4',
        borderStrong: '#dcc7b7',
        success: '#2ea56c',
        successSoft: '#e7f7ef',
        info: '#5b8ef5',
        infoSoft: '#eaf2ff',
        warning: '#f08a35',
        warningSoft: '#fff1e4',
        danger: '#d45c4a',
        dangerSoft: '#fdebe8',
        white: '#ffffff',
        orange: {
          50: '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
        },
      },
      borderRadius: {
        sm: '12px',
        md: '16px',
        lg: '20px',
        xl: '24px',
        xxl: '28px',
        pill: '9999px',
      },
      spacing: {
        screen: '20px',
        card: '16px',
      },
    },
  },
  plugins: [],
};
